# Fibonacci Spiral Strategy
# Based on the golden spiral and Fibonacci sequence for optimal growth patterns

name: "Fibonacci Spiral"
description: "Uses Fibonacci ratios and spiral dynamics for natural optimization patterns, mimicking growth in nature"

# Core parameters based on Fibonacci sequence
parameters:
  # Fibonacci-based thresholds
  ultra_rare_threshold: 0.0618   # 1/φ (golden ratio reciprocal)
  rare_threshold: 0.1618        # φ - 1
  
  # Acceptance rates using Fibonacci ratios
  ultra_rare_accept_rate: 0.987  # F(16)/F(17) convergence
  rare_accept_rate: 0.854        # F(11)/F(13)
  common_accept_rate: 0.618      # φ - 1 (golden ratio)
  no_constraint_accept_rate: 0.034  # 1/F(8)
  
  # Phase thresholds following Fibonacci growth
  early_game_threshold: 0.236    # F(5)/F(8)
  mid_game_threshold: 0.618      # Golden ratio - 1
  
  # Spiral growth parameters
  spiral_growth_factor: 1.618    # Golden ratio φ
  fibonacci_scaling: true
  
  # Multi-attribute bonuses using Fibonacci numbers
  multi_attr_bonus: 1.618       # φ
  dual_rare_bonus: 2.618        # φ²
  fibonacci_progression: true

# Fibonacci-specific mechanisms
fibonacci_mechanics:
  # Spiral acceptance pattern
  spiral_pattern:
    enabled: true
    rotation_angle: 137.5        # Golden angle in degrees
    spiral_tightness: 1.618      # φ factor
    
  # Sequence-based progression
  sequence_progression:
    enabled: true
    use_sequence: [1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
    progression_scaling: 0.618   # Inverse golden ratio
    
  # Golden section search for optimization
  golden_section_search:
    enabled: true
    tolerance: 0.001
    max_iterations: 21           # F(8)

# Phase-specific behavior using natural growth patterns
phases:
  early:
    description: "Seed phase - plant strongest foundations"
    fibonacci_selectivity: true
    growth_factor: 1.618
    
  mid:
    description: "Growth phase - fibonacci expansion"
    spiral_acceptance: true
    golden_ratio_optimization: true
    
  late:
    description: "Maturation phase - approaching phi convergence"
    convergence_seeking: true
    fibonacci_fine_tuning: true
    
  panic:
    description: "Emergency growth burst"
    fibonacci_emergency: true
    accept_golden_ratio: 0.618

# Natural mathematics integration
natural_patterns:
  phyllotaxis: true             # Leaf arrangement patterns
  shell_spiral: true            # Nautilus shell growth
  pine_cone_scaling: true       # Pine cone Fibonacci spirals
  sunflower_seeds: true         # Sunflower seed arrangement

# Scenario adjustments using mathematical constants
scenario_adjustments:
  1:  # Friday Night
    ultra_rare_threshold: 0.0618
    spiral_growth_factor: 1.618
    
  2:  # Saturday Night (creative ultra-rare)
    ultra_rare_threshold: 0.0382  # F(3)/F(8)
    ultra_rare_accept_rate: 0.993  # Near φ/2
    fibonacci_emergency_mode: true
    
  3:  # Sunday Night (complex multi-constraint)
    multi_attr_bonus: 2.618      # φ²
    fibonacci_balancing: true
    golden_section_optimization: true

# Mathematical convergence properties
convergence:
  phi_convergence: true
  lucas_numbers: false          # Optional Lucas sequence
  tribonacci: false            # Optional Tribonacci extension
  fibonacci_primality: true    # Use Fibonacci primes