# Harmonic Series Strategy
# Uses harmonic series H_n = 1 + 1/2 + 1/3 + ... + 1/n for logarithmic growth optimization

name: "Harmonic Series"
description: "Applies harmonic series and reciprocal sum dynamics for slowly divergent but well-controlled optimization"

# Core parameters based on harmonic series properties
parameters:
  # Harmonic-based thresholds using reciprocal sequences
  ultra_rare_threshold: 0.0833   # 1/12 (12th harmonic term)
  rare_threshold: 0.1667         # 1/6 (6th harmonic term)
  
  # Acceptance rates using harmonic sums
  ultra_rare_accept_rate: 0.9167 # 11/12 (complement of 12th term)
  rare_accept_rate: 0.8333       # 5/6 (complement of 6th term)  
  common_accept_rate: 0.6366     # 2/π ≈ 0.6366 (Euler's constant related)
  no_constraint_accept_rate: 0.0357  # 1/28 (28th harmonic term)
  
  # Phase thresholds using harmonic convergence
  early_game_threshold: 0.2500   # 1/4 (4th harmonic term)
  mid_game_threshold: 0.6931     # ln(2) ≈ H(∞) - H(1) pattern
  
  # Harmonic series parameters
  series_terms: 100              # Compute H_100
  euler_mascheroni: 0.5772156649 # γ = lim(H_n - ln(n))
  
  # Key harmonic sums
  h_10: 2.9289682540            # H_10 ≈ 2.929
  h_50: 4.4991886272            # H_50 ≈ 4.499  
  h_100: 5.1873775177           # H_100 ≈ 5.187
  
  # Reciprocal weighting
  reciprocal_emphasis: true
  logarithmic_scaling: true

# Harmonic series mechanics
harmonic_mechanics:
  # Series computation
  series_computation:
    enabled: true
    partial_sums: true          # S_n = Σ(k=1 to n) 1/k
    remainder_estimation: true   # H_∞ - H_n ≈ 1/(2n)
    
  # Asymptotic behavior
  asymptotic_analysis:
    enabled: true
    logarithmic_growth: true    # H_n ≈ ln(n) + γ + 1/(2n)
    euler_constant_approach: true # γ = lim(H_n - ln(n))
    
  # Reciprocal relationships
  reciprocal_patterns:
    enabled: true
    reciprocal_weighting: true  # Weight by 1/k
    harmonic_mean: true         # n/(Σ 1/x_i) applications
    
  # Convergence properties
  convergence_analysis:
    enabled: true
    divergence_rate: true       # Series diverges like ln(n)
    slow_divergence: true       # Slower than geometric series

# Mathematical properties of harmonic series
mathematical_properties:
  # Divergence proof
  divergence_properties:
    enabled: true
    cauchy_condensation: true   # Test for divergence
    comparison_test: true       # Compare with ln(n)
    
  # Asymptotic expansion
  asymptotic_expansion:
    enabled: true
    euler_maclaurin_formula: true # H_n = ln(n) + γ + 1/(2n) - 1/(12n²) + ...
    
  # Related series
  related_series:
    enabled: true
    alternating_harmonic: true  # ln(2) = 1 - 1/2 + 1/3 - 1/4 + ...
    p_series: false             # Σ 1/k^p for p > 1 converges
    
  # Number theory connections
  number_theory:
    enabled: true
    prime_harmonic_series: true # Σ 1/p diverges (primes)
    divisor_function_connections: false

# Phase-specific harmonic behaviors
phases:
  early:
    description: "Initial terms - large harmonic contributions"
    large_term_emphasis: true
    first_harmonics_focus: true
    reciprocal_optimization: true
    
  mid:
    description: "Logarithmic growth - steady accumulation"
    logarithmic_pattern_following: true
    euler_constant_approximation: true
    partial_sum_optimization: true
    
  late:
    description: "Asymptotic regime - refined estimates"
    asymptotic_formula_application: true
    remainder_term_precision: true
    
  panic:
    description: "Harmonic emergency - dominant term focus"
    emergency_harmonic_weight: 0.6931  # ln(2)
    large_reciprocal_fallback: true

# Applications in analysis and number theory
analysis_applications:
  # Real analysis
  real_analysis:
    enabled: true
    improper_integrals: true    # ∫(1 to ∞) 1/x dx = ∞
    integral_test: true         # Series/integral comparison
    
  # Complex analysis
  complex_analysis:
    enabled: false              # Riemann zeta ζ(1) = H_∞
    
  # Probability theory
  probability_applications:
    enabled: true
    coupon_collector: true      # Expected time ≈ n·H_n
    random_harmonic: false      # Stochastic versions
    
  # Algorithm analysis
  algorithmic_applications:
    enabled: true
    complexity_analysis: true   # Many algorithms have H_n complexity
    quick_select_average: true  # Average case analysis

# Special harmonic sequences and generalizations
harmonic_generalizations:
  # Generalized harmonic numbers
  generalized_harmonic:
    enabled: false              # H_n^(r) = Σ 1/k^r
    
  # Weighted harmonic series
  weighted_harmonic:
    enabled: true
    arithmetic_weights: true    # Σ w_k/k
    
  # Harmonic-geometric mean inequality
  mean_inequalities:
    enabled: true
    hm_am_gm_qm: true          # Harmonic ≤ Arithmetic ≤ Geometric ≤ Quadratic
    
  # Continued fractions
  continued_fraction_connections:
    enabled: false              # Advanced connections

# Computational aspects
computational_harmonic:
  # Efficient computation
  efficient_computation:
    enabled: true
    partial_sum_caching: true   # Store computed H_k values
    asymptotic_approximation: true # Use formula for large n
    
  # Precision considerations
  precision_handling:
    enabled: true
    floating_point_accuracy: true
    summation_order: true       # Add smallest terms first
    
  # Optimization techniques
  optimization_methods:
    enabled: true
    euler_maclaurin_acceleration: true
    richardson_extrapolation: false

# Scenario adjustments using harmonic properties
scenario_adjustments:
  1:  # Friday Night
    harmonic_term_weighting: "linear"
    euler_constant_factor: 1.1
    reciprocal_emphasis: 1.3
    
  2:  # Saturday Night (creative ultra-rare)
    ultra_rare_threshold: 0.0417  # 1/24 (24th harmonic)
    ultra_rare_accept_rate: 0.9958 # 23/24 + boost
    high_precision_harmonic: true
    
  3:  # Sunday Night (multi-constraint)
    multi_harmonic_balancing: true
    weighted_harmonic_optimization: true
    logarithmic_scaling_multi: true

# Historical and mathematical significance
historical_significance:
  # Ancient mathematics
  ancient_roots: true           # Known to medieval mathematicians
  
  # Modern analysis
  analysis_foundation: true     # Important in real analysis
  
  # Applications
  practical_importance: true    # Algorithm analysis, probability
  
  # Famous problems
  basel_problem_connection: true # ζ(2) = π²/6, but ζ(1) = ∞

# Related mathematical constants
harmonic_constants:
  euler_mascheroni_gamma: 0.5772156649    # γ
  natural_logarithm_2: 0.6931471806      # ln(2)
  riemann_zeta_2: 1.6449340668           # π²/6 = ζ(2)
  
  # Approximation constants
  stirling_constant: 2.5066282746        # √(2π)
  
# Connections to other series
series_connections:
  # Convergent series
  p_series_p_greater_1: false   # Σ 1/k^p, p > 1
  geometric_series: false       # Σ r^k, |r| < 1
  
  # Divergent series
  arithmetic_series: false      # Σ k (much faster divergence)
  
  # Conditionally convergent
  alternating_harmonic: true    # Σ (-1)^(k+1)/k = ln(2)
  
  # Special functions
  riemann_zeta_function: true   # ζ(1) = harmonic series
  gamma_function: false         # Γ(s) connections

# Optimization applications
optimization_applications:
  # Resource allocation
  resource_allocation:
    enabled: true
    diminishing_returns: true   # Each additional unit less valuable
    marginal_utility: true      # Economic applications
    
  # Scheduling and algorithms
  algorithmic_optimization:
    enabled: true
    load_balancing: true        # Harmonic weights
    probabilistic_algorithms: true
    
  # Machine learning
  learning_applications:
    enabled: false              # Learning rate schedules
    
# Advanced harmonic theory
advanced_theory:
  # Analytic number theory
  analytic_number_theory:
    enabled: false              # Dirichlet series, L-functions
    
  # Asymptotic analysis
  asymptotic_methods:
    enabled: true
    saddle_point_method: false
    stationary_phase: false
    
  # Special function theory
  special_functions:
    enabled: false              # Polygamma functions
    
  # Fourier analysis connections
  fourier_connections:
    enabled: false              # Harmonic analysis vs harmonic series