# Prime Sieve Strategy
# Uses prime number theory and the Sieve of Eratosthenes for selective optimization

name: "Prime Sieve"
description: "Applies prime number theory, using selectivity patterns based on the fundamental building blocks of mathematics"

# Core parameters based on prime number theory
parameters:
  # Prime-based thresholds using notable primes
  ultra_rare_threshold: 0.0701   # 1/prime(4) = 1/7 ≈ 0.071  
  rare_threshold: 0.1429         # 1/prime(3) = 1/7
  
  # Acceptance rates using prime ratios
  ultra_rare_accept_rate: 0.9697 # 97/100 (97 is prime)
  rare_accept_rate: 0.8913       # 89/100 + 13/100 (both prime)
  common_accept_rate: 0.6111     # 61/100 + 11/100 (both prime) 
  no_constraint_accept_rate: 0.0317  # 31/1000 + 7/1000 (both prime)
  
  # Phase thresholds using prime ratios
  early_game_threshold: 0.23     # 23/100 (23 is prime)
  mid_game_threshold: 0.67       # 67/100 (67 is prime)
  
  # Prime sequence parameters
  prime_sequence: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]
  mersenne_primes: [3, 7, 31, 127]  # 2^n - 1 primes
  twin_primes: [[3,5], [5,7], [11,13], [17,19], [29,31], [41,43]]
  
  # Sieve parameters
  sieve_size: 1000
  primality_testing: true

# Prime number mechanics
prime_mechanics:
  # Sieve of Eratosthenes behavior
  sieve_filtering:
    enabled: true
    composite_rejection: true    # Reject composites more often
    prime_preference: true       # Prefer prime-indexed decisions
    
  # Prime gap analysis
  prime_gaps:
    enabled: true
    gap_weighting: true         # Weight decisions by prime gaps
    twin_prime_bonus: true      # Bonus for twin prime patterns
    
  # Goldbach conjecture application
  goldbach_pairing:
    enabled: true
    even_sum_optimization: true  # Every even > 2 = prime + prime
    
  # Riemann hypothesis connection
  zeta_function:
    enabled: false              # Advanced: use ζ(s) zeros
    critical_line: false        # Re(s) = 1/2 applications

# Prime testing and generation
prime_algorithms:
  # Primality tests
  miller_rabin: true
  fermat_test: false           # Less reliable
  
  # Prime generation
  sieve_eratosthenes: true
  wheel_factorization: false
  
  # Special primes
  mersenne_detection: true     # 2^p - 1
  fermat_numbers: false        # 2^(2^n) + 1
  sophie_germain: true         # p where 2p+1 also prime

# Phase-specific prime behaviors
phases:
  early:
    description: "Prime foundation - sieve out composites"
    strict_primality: true
    composite_avoidance: true
    sieve_aggressive: true
    
  mid:
    description: "Prime gaps - optimize spacing"
    gap_analysis: true
    twin_prime_seeking: true
    goldbach_optimization: true
    
  late:
    description: "Prime convergence - number theory limits"
    prime_number_theorem: true  # π(x) ~ x/ln(x)
    bertrand_postulate: true    # Prime between n and 2n
    
  panic:
    description: "Prime emergency - fundamental acceptance"
    accept_all_primes: true
    prime_fallback: 0.71        # Meissel-Lehmer constant

# Number theory applications
number_theory:
  # Distribution of primes
  prime_counting: true         # π(x) function
  prime_gaps_distribution: true
  
  # Multiplicative functions
  euler_totient: true          # φ(n)
  mobius_function: true        # μ(n)
  
  # Diophantine equations
  linear_congruences: true
  quadratic_residues: true

# Special prime sequences and patterns
prime_patterns:
  # Arithmetic progressions
  arithmetic_primes: true      # Primes in AP
  green_tao_theorem: true      # Arbitrarily long AP of primes
  
  # Prime constellations
  prime_clusters: true
  prime_k_tuples: true
  
  # Palindromic primes
  palindromic: false
  emirp_primes: false          # Primes backwards

# Scenario adjustments using prime theory
scenario_adjustments:
  1:  # Friday Night
    twin_prime_bonus: 2.0      # Enhanced twin prime preference
    prime_sequence_limit: 23    # Use primes up to 23
    
  2:  # Saturday Night (creative ultra-rare)
    ultra_rare_threshold: 0.0431  # 43/1000 (43 is prime)
    mersenne_prime_mode: true     # Use Mersenne primes
    ultra_rare_accept_rate: 0.997  # 997 is prime
    
  3:  # Sunday Night (multi-constraint)  
    goldbach_conjecture_mode: true
    prime_constellation_bonus: true
    arithmetic_progression_primes: true

# Mathematical constants from prime theory
prime_constants:
  meissel_lehmer: 0.7071067812   # Related to prime distribution
  twin_prime_constant: 0.6601618158
  brun_constant: 1.9021605831    # Sum of reciprocals of twin primes
  
# Advanced prime theory (experimental)
advanced_theory:
  # Analytical number theory
  riemann_zeta_zeros: false
  explicit_formula: false
  
  # Computational number theory
  quadratic_sieve: false
  elliptic_curve_method: false
  
  # Probabilistic methods
  erdos_kac_theorem: true      # Normal distribution of prime factors
  hardy_ramanujan: true        # Average number of prime factors