# Stirling Numbers Strategy
# Uses Stirling numbers of both kinds for advanced combinatorial optimization

name: "Stirling Numbers"
description: "Applies Stirling numbers of the first and second kind for sophisticated combinatorial decision patterns"

# Core parameters based on Stirling numbers S(n,k) and s(n,k)
parameters:
  # Stirling-based thresholds using combinatorial ratios
  ultra_rare_threshold: 0.0714   # 1/S(4,2) = 1/7 (second kind)
  rare_threshold: 0.1667         # 1/s(4,2) = 1/6 (first kind, unsigned)
  
  # Acceptance rates using Stirling ratios
  ultra_rare_accept_rate: 0.8571 # 6/7 = (S(4,2)-1)/S(4,2)
  rare_accept_rate: 0.8333       # 5/6 = (s(4,2)-1)/s(4,2)
  common_accept_rate: 0.5000     # S(3,2)/S(3,1) = 3/1, normalized
  no_constraint_accept_rate: 0.0294  # 1/S(5,3) = 1/25
  
  # Phase thresholds using Stirling triangle properties
  early_game_threshold: 0.2500   # Related to small Stirling values
  mid_game_threshold: 0.6250     # Balanced Stirling region
  
  # Stirling numbers of the second kind: S(n,k) = partitions of n objects into k non-empty subsets
  stirling_second: {
    "S(3,2)": 3, "S(4,2)": 7, "S(4,3)": 6, "S(5,2)": 15,
    "S(5,3)": 25, "S(5,4)": 10, "S(6,3)": 90, "S(6,4)": 65
  }
  
  # Stirling numbers of the first kind: s(n,k) = signed coefficients in x(x-1)...(x-n+1)
  stirling_first: {
    "s(3,2)": 3, "s(4,2)": 11, "s(4,3)": 6, "s(5,2)": 50,
    "s(5,3)": 35, "s(5,4)": 10, "s(6,3)": 225, "s(6,4)": 85
  }
  
  # Triangle computation parameters
  triangle_depth: 12
  both_kinds: true

# Stirling number mechanics
stirling_mechanics:
  # Second kind (set partitions)
  second_kind:
    enabled: true
    set_partitions: true        # S(n,k) = ways to partition n objects into k subsets
    bell_number_connection: true # B_n = Σ S(n,k)
    recurrence: true            # S(n,k) = k·S(n-1,k) + S(n-1,k-1)
    
  # First kind (unsigned cycles)
  first_kind:
    enabled: true
    cycle_structure: true       # |s(n,k)| = permutations of n with k cycles
    factorial_expansion: true   # x^n = Σ s(n,k) x(x+1)...(x+k-1)
    unsigned_interpretation: true
    
  # Triangular arrays
  triangular_structure:
    enabled: true
    stirling_triangles: true    # Both triangular arrays
    recurrence_relations: true
    boundary_conditions: true   # S(n,0)=0, S(0,0)=1, etc.

# Combinatorial interpretations
combinatorial_interpretations:
  # Set partitions (second kind)
  set_partition_theory:
    enabled: true
    block_structure: true       # Partition into non-empty blocks
    equivalence_relations: true
    onto_functions: true        # Surjective functions {1..n} → {1..k}
    
  # Permutation cycles (first kind)
  cycle_theory:
    enabled: true
    cycle_decomposition: true   # Permutations decomposed into disjoint cycles
    cycle_index: true           # Polynomial representation
    
  # Polynomial connections
  polynomial_connections:
    enabled: true
    falling_factorials: true   # (x)_n = x(x-1)...(x-n+1)
    rising_factorials: true     # x^(n) = x(x+1)...(x+n-1)

# Phase-specific Stirling behaviors
phases:
  early:
    description: "Small partitions - basic Stirling structures"
    small_stirling_focus: true
    simple_partitions: true
    cycle_minimization: true
    
  mid:
    description: "Balanced structures - optimize k parameter"
    stirling_optimization: true
    balanced_k_values: true
    recurrence_utilization: true
    
  late:
    description: "Large structures - asymptotic behavior"
    large_stirling_application: true
    asymptotic_approximation: true
    
  panic:
    description: "Stirling emergency - simple structures"
    emergency_stirling: 0.25    # Simple ratio
    basic_structure_fallback: true

# Mathematical properties
mathematical_properties:
  # Recurrence relations
  recurrence_relations:
    second_kind_recurrence: true # S(n,k) = k·S(n-1,k) + S(n-1,k-1)
    first_kind_recurrence: true  # s(n,k) = (n-1)·s(n-1,k) + s(n-1,k-1)
    
  # Generating functions
  generating_functions:
    exponential_gf_second: true  # For fixed k: (e^x - 1)^k / k!
    ordinary_gf_first: false    # More complex for first kind
    
  # Asymptotic behavior
  asymptotic_analysis:
    enabled: true
    stirling_approximation: true # For large n
    maximum_values: true         # S(n,k) max at k ≈ n/log(n)
    
  # Orthogonality relations
  orthogonality:
    enabled: true
    inverse_relations: true      # Stirling numbers are inverses

# Advanced Stirling theory
advanced_theory:
  # Generalized Stirling numbers
  generalizations:
    enabled: false              # r-Stirling numbers, etc.
    
  # q-analogues
  q_stirling:
    enabled: false              # q-deformed versions
    
  # Multivariate generalizations
  multivariate:
    enabled: false              # Multiple variables
    
  # Rook polynomials
  rook_polynomials:
    enabled: false              # Related combinatorial objects

# Computational aspects
computational_stirling:
  # Efficient computation
  efficient_algorithms:
    enabled: true
    dynamic_programming: true   # Build triangles row by row
    recurrence_optimization: true
    
  # Memory management
  memory_optimization:
    enabled: true
    space_efficient: true       # Only store needed rows
    
  # Numerical stability
  numerical_considerations:
    enabled: true
    overflow_prevention: true   # Large Stirling numbers
    modular_arithmetic: true    # When appropriate

# Connections to other mathematics
mathematical_connections:
  # Special functions
  special_functions:
    enabled: false              # Incomplete gamma functions
    
  # Number theory
  number_theory:
    enabled: true
    divisibility_properties: true
    congruences: false          # More advanced
    
  # Analysis
  analytical_connections:
    enabled: false              # Analytic combinatorics
    
  # Algebra
  algebraic_aspects:
    enabled: true
    symmetric_functions: false  # Advanced algebra
    group_theory: false         # Permutation groups

# Scenario adjustments using Stirling theory
scenario_adjustments:
  1:  # Friday Night
    stirling_second_emphasis: 1.4
    partition_optimization: true
    moderate_k_values: true
    
  2:  # Saturday Night (creative ultra-rare)
    ultra_rare_threshold: 0.0111  # 1/S(6,4) = 1/65
    ultra_rare_accept_rate: 0.9846 # 64/65
    large_stirling_precision: true
    
  3:  # Sunday Night (multi-constraint)
    dual_stirling_optimization: true
    cycle_partition_balancing: true
    multi_k_coordination: true

# Applications in optimization
optimization_applications:
  # Combinatorial optimization
  combinatorial_optimization:
    enabled: true
    partition_problems: true    # Optimal partitioning
    assignment_problems: false  # More complex variants
    
  # Network problems
  network_applications:
    enabled: false              # Graph partitioning variants
    
  # Resource allocation
  resource_allocation:
    enabled: true
    group_formation: true       # Optimal grouping strategies
    
  # Scheduling
  scheduling_applications:
    enabled: false              # Task assignment problems

# Stirling constants and special values
stirling_constants:
  # Maximum Stirling numbers (for small n)
  max_S_4: 7                   # S(4,2) is maximum for n=4
  max_S_5: 25                  # S(5,3) is maximum for n=5
  
  # Growth estimates
  approximate_max_k: "n/ln(n)" # k that maximizes S(n,k)
  
  # Asymptotic constants
  stirling_asymptotic: 1.0     # Various asymptotic constants

# Special cases and identities
special_cases:
  # Boundary conditions
  boundary_values:
    S_n_0: 0                   # S(n,0) = 0 for n > 0
    S_0_0: 1                   # S(0,0) = 1
    S_n_n: 1                   # S(n,n) = 1
    S_n_1: 1                   # S(n,1) = 1
    
  # Special relationships
  special_relationships:
    bell_sum: true             # B_n = Σ S(n,k)
    factorial_expansion: true   # n! = Σ s(n,k) for first kind
    
  # Symmetric properties
  symmetry_properties:
    second_kind_symmetry: false # Not symmetric
    first_kind_symmetry: false  # Not symmetric

# Computational complexity
complexity_analysis:
  # Time complexity
  time_complexity:
    single_value: "O(nk)"      # Computing S(n,k) or s(n,k)
    full_triangle: "O(n³)"     # Computing full triangle
    
  # Space complexity
  space_complexity:
    naive_approach: "O(n²)"    # Store full triangle
    optimized: "O(n)"          # Store only needed rows
    
  # Practical considerations
  practical_limits:
    overflow_threshold: 20     # Approximate limit for standard integers
    precision_requirements: true

# Research connections
research_aspects:
  # Open problems
  open_questions:
    enabled: false             # Mostly well-understood
    
  # Active research
  current_research:
    enabled: false             # Generalizations and applications
    
  # Historical development
  historical_importance:
    enabled: true
    james_stirling: true       # Named after James Stirling
    combinatorial_significance: true