# Ultimate Mathematical Optimization (UMO)

name: "Ultimate"
description: "Mathematically optimal strategy using Lagrangian optimization, game theory, and information theory"

parameters:
  # Lagrangian optimization
  lagrange_multiplier_y: 3.2
  lagrange_multiplier_w: 3.2
  capacity_shadow_price: 1.8
  
  # Dynamic programming
  bellman_discount: 0.996
  exploration_epsilon: 0.025
  learning_rate: 0.06
  
  # Information theory
  entropy_threshold: 1.35
  mutual_information_weight: 0.40
  kl_divergence_penalty: 0.12
  
  # Game theory
  nash_equilibrium_mixing: 0.20
  regret_minimization_eta: 0.10
  opponent_modeling_depth: 2
  
  # Convex optimization
  gradient_momentum: 0.91
  projection_tolerance: 0.000001
  convergence_threshold: 0.00001
  
  # Martingale theory
  risk_aversion: 0.58
  variance_penalty: 0.14
  confidence_level: 0.98

scenario_adjustments:
  1:
    # Scenario 1 specific optimizations
    lagrange_multiplier_y: 2.9
    lagrange_multiplier_w: 2.9
    capacity_shadow_price: 1.65
    learning_rate: 0.08
    entropy_threshold: 1.25
    risk_aversion: 0.52
    nash_equilibrium_mixing: 0.15