# Ultimate2 Mathematical Optimization

name: "Ultimate2"
description: "Mathematically perfected Ultimate with hierarchical optimization and guaranteed constraint satisfaction"

parameters:
  # Hierarchical optimization (PRIMARY FIX)
  constraint_priority_weight: 1000000.0   # Effectively infinite priority for constraints
  rejection_optimization_weight: 1.0      # Secondary objective: minimize rejections  
  feasibility_threshold: 0.9995           # 99.95% constraint satisfaction guarantee
  
  # Hard constraint barriers (CORRECTED from Ultimate)
  barrier_strength: 1500.0                # Strong exponential barriers
  violation_penalty: 1000000.0            # Effectively infinite penalty for violations
  safety_buffer: 8                        # Conservative safety margin
  
  # Immediate Lagrange updates (FIXED from Ultimate)  
  lambda_response_rate: 8.0               # Immediate strong response to deficits
  deficit_multiplier: 25.0                # Amplified response to violations
  learning_momentum: 0.0                  # No momentum - immediate updates only
  
  # Phase management (3-phase optimization)
  phase1_cutoff: 0.30                     # Early: selective but constraint-safe
  phase2_cutoff: 0.70                     # Mid: balanced constraint+efficiency  
  phase3_cutoff: 1.0                      # Late: pure constraint focus
  
  # Corrected information theory (FIXED priorities)
  constraint_mutual_info_weight: 2.0      # High value for constraint helpers
  non_constraint_mutual_info_weight: 0.05 # Very low value for non-helpers
  entropy_balance_bonus: 1.0              # Reward balanced progress
  
  # Risk management (CORRECTED priorities)
  constraint_risk_aversion: 0.02          # Very conservative about violations
  rejection_risk_aversion: 0.6            # Aggressive about minimizing rejections
  
  # Exploration control (NO harmful exploration)
  safe_exploration_rate: 0.005            # Minimal safe exploration only
  no_exploration_when_risk: true          # Never explore when constraints at risk
  
  # Mathematical precision
  convergence_tolerance: 0.0000000001     # Ultra-high precision
  numerical_stability_epsilon: 0.000000000001

scenario_adjustments:
  1:
    # Scenario 1 specific Ultimate2 optimization
    barrier_strength: 2000.0              # Even stronger barriers
    lambda_response_rate: 10.0            # Faster constraint response
    deficit_multiplier: 30.0              # Higher deficit sensitivity
    constraint_mutual_info_weight: 2.5    # Higher constraint helper value
    phase1_cutoff: 0.25                   # Earlier constraint focus
    phase2_cutoff: 0.65                   # Shorter mid-phase
    safety_buffer: 5                      # Tighter safety margins